# Generated by Django 4.1.2 on 2022-10-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('store_owner', 'Owner'), ('client', 'Client')], max_length=20),
        ),
    ]
